# preview_dummy_dashboard.R
# ─────────────────────────────────────────────────────────────────────────────
# Dev helper: builds analysis-ready tables from the FAKE GGIR output generated by
# data/example/dummy_data/generate_ggir_outputs.py, then launches the Shiny
# dashboard against them — a fast way to preview the dashboard without waiting
# on a real (or even real-dummy) GGIR run.
#
# This is NOT real data. Run generate_ggir_outputs.py first if
# data/processed/dummy_output/ doesn't exist yet:
#   python data/example/dummy_data/generate_ggir_outputs.py
#
# Temporarily points config.yaml's paths.data_processed at
# data/processed/dummy_output/ (isolated from real output — see bug #27) so
# 03_build_summaries.R writes there instead of the real location, then restores
# config.yaml exactly (byte-for-byte via readLines/writeLines) on normal
# completion or any R-level error — same pattern as scripts/ci/run_example_pipeline.R.
#
# Known limitation (not specific to this script): a hard process kill (not a
# normal R error) skips the restore, since tryCatch/finally only intercepts
# R-level conditions, not the process being terminated outright. If config.yaml
# is ever found pointed at a non-default data_processed unexpectedly, check for
# this — restore it from git or re-run this script normally to fix it.
#
# Run from the r/ directory: Rscript ../scripts/dev/preview_dummy_dashboard.R
# ─────────────────────────────────────────────────────────────────────────────

library(yaml)

message("")
message("═══ DUMMY DASHBOARD PREVIEW — NOT REAL DATA ═══════════════════════")
message("")

dummy_dir <- "../data/processed/dummy_output"
if (!dir.exists(dummy_dir) || length(list.files(dummy_dir, recursive = TRUE)) == 0) {
  stop(
    "data/processed/dummy_output/ not found or empty.\n",
    "Run this first, from the repo root:\n",
    "  python data/example/dummy_data/generate_ggir_outputs.py",
    call. = FALSE
  )
}

cfg_path <- "../config.yaml"
original_lines <- readLines(cfg_path, warn = FALSE)

# tryCatch(..., finally = ...) rather than on.exit(): on.exit() only attaches
# to a function's call frame, and this script runs at top level, so it would
# silently never fire. finally always runs, on success, error, or interruption.
tryCatch({
  cfg <- yaml::read_yaml(cfg_path)
  cfg$paths$data_processed <- "../data/processed/dummy_output"
  yaml::write_yaml(cfg, cfg_path)
  message("[preview] config.yaml temporarily set to paths.data_processed: ",
          "../data/processed/dummy_output")
  message("")

  source("pipeline/03_build_summaries.R")

  message("")
  message("[preview] Launching Shiny dashboard against the fake data...")
  shiny::runApp("shiny", launch.browser = TRUE)
}, finally = {
  writeLines(original_lines, cfg_path)
  message("[preview] config.yaml restored to its original contents")
})
